language: java
jdk:
  - openjdk8
env:
  - IDEA_VERSION=IC-2016.3.8
  - IDEA_VERSION=IC-2017.3.6
  - IDEA_VERSION=IC-2018.2.7
  - IDEA_VERSION=IC-2018.3.4
  - IDEA_VERSION=IC-191.5701.16
install: sed -i '/ideaVersion=/c\ideaVersion='"$IDEA_VERSION"'' gradle.properties