language: java
jdk:
  - openjdk8
env:
  # see https://www.jetbrains.com/idea/download/previous.html
  - IDEA_VERSION=IC-2016.3.8
  - IDEA_VERSION=IC-2017.3.6
  - IDEA_VERSION=IC-2018.2.7
  - IDEA_VERSION=IC-2018.3.5
  - IDEA_VERSION=IC-2019.1.3
  - IDEA_VERSION=IC-2019.2.4
  - IDEA_VERSION=IC-2019.3
install:
  - sed -i '/ideaVersion=/c\ideaVersion='"$IDEA_VERSION"'' gradle.properties
