language: java
jdk:
  - openjdk8
env:
  # see https://www.jetbrains.com/idea/download/previous.html
  # and https://www.jetbrains.com/intellij-repository/snapshots/
  - IDEA_VERSION=IC-2016.2
  - IDEA_VERSION=IC-2016.3.8
  - IDEA_VERSION=IC-2017.3.6
  - IDEA_VERSION=IC-2018.2.8
  - IDEA_VERSION=IC-2018.3.6
  - IDEA_VERSION=IC-2019.1.4
  - IDEA_VERSION=IC-2019.2.4
  - IDEA_VERSION=IC-2019.3.3
  - IDEA_VERSION=IC-201-EAP-SNAPSHOT
install:
  - ./gradlew -PideaVersion="$IDEA_VERSION" assemble
script:
  - ./gradlew check --stacktrace
